import type { NextPage } from 'next';
import Head from 'next/head';
import MainPage from './mainpage'

const Home: NextPage = () => (
    <div>
        <Head>
            <title>WordBlast</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <MainPage/>
    </div>
);

export default Home;
